### ISSUE TITLE
Go fixed asset implementation doesn't work with the rich query or range query workloads

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper-benchmarks#189]
Similar to Java for the contract api implementation you get the error
```
 Failed to perform query transaction [paginatedRichQuery] using arguments [{"selector":{"docType":"fixed-asset","creator":"client_nomatch","byteSize":1000}},2],  with error: Error: Incorrect number of params. Expected 3, received 2
```

Need to see what happens with fixed-asset-base where the contract-api doesn't check the parameters.

**Comment by fraVlaca** [comment]
with fixed asset base I also run into problems.
I am able tu submit trasaction but they are then all flagged as unfinished. finally, I then get 
`Failed to perform query transaction [paginatedRichQuery] using arguments [{"selector":{"docType":"fixed-asset","creator":"client3"}},10,],  with error: GatewayError: 4 DEADLINE_EXCEEDED: evaluate timeout expired`

**Comment by fraVlaca** [comment]
sometimes even the creation of the assets fails:
`with error: TimeoutError: Event strategy not satisfied within the timeout period. No response received from peers: peer0.org1.example.com:7051`

**Comment by fraVlaca** [comment]
just run the node fixed asset chaincode as well and it actually give same error that you reported by dkelsey for the java one:
```
Failed to perform query transaction [paginatedRichQuery] using arguments [{"selector":{"docType":"fixed-asset","creator":"client1"}},10,],  with error: Error: error in simulation: transaction returned with failure: Error: Expected 2 parameters, but 3 have been supplied
```

**Comment by fraVlaca** [comment]
The node chaincode uses default parameters while the go one doesn't

In the benchmark we do provide only the required parameters(2 out of 3 for rich query and 3 out of 4 for range query), which works for the node chaincode that has the last parameter as an optional default one while it does not work for the go one.

However, if you try to actually set the third parameter (forth for range query) the go one works fine but the node one doesn't
as far as I understood chaincode functions have a fixed signature with no optional parameters. This is an arbitrary choice since GRPC supports optional parameters by setting them to a default value if missing. I don't really see it documented anywhere but by browsing different issues I could find the answer...

I'll go ahead removing the optional parameter from the node chaincode and provide all of the arguments in the benchmark call.




[10:00](https://ibm-blockchain.slack.com/archives/D026U1DQGSH/p1657184436667179)
I'll go ahead removing the optional parameter from the node chaincode and provide all of the arguments in the benchmark call

**Comment by fraVlaca** [comment]
By reducing the number of assets created everything works fine. however, if we keep the current setting, creating 8000 assets for each worker and size, then around a third of query timeout.
By looking at the couch db logs we see that they eventually finish but after more than 20 seconds
<img width="1448" alt="Screenshot 2022-07-07 at 10 52 57" src="https://user-images.githubusercontent.com/86831094/177746457-bf870d7d-e74f-4f1d-84fe-c01807235350.png">
The question then becomes, is the problem around the couch db query? Increasing the number of assets it takes exponentially longer for more and more queries to complete.
The queries do eventually complete ok. After debugging the chaincode we do not see any problem during the creation of the asset, then the problems seams related to couchdb. We are not increasing the tps at all but just the number of the asset stored in the db, might that be the problem?
