### ISSUE TITLE
when run 'Run the benchmark using the Caliper CLI command:',there is a wrong as follow:

### ISSUE THREAD

**Issue by dretrtg** [hyperledger/caliper-benchmarks#79]
Error while performing "init" step: Error: Couldn't read configuration binary for mychannel: EISDIR: illegal operation on a directory, read

**Comment by siler23** [comment]
Perhaps it would be better for you to ask this in Rocket.Chat in the caliper channel (https://chat.hyperledger.org/channel/caliper)? I think you can get more help there since it seems like a configuration issue rather than an issue with the caliper-benchmarks repository and I believe the people in that chat can help you.

Specifically, the binary specified in `configBinary` in your network configuration file seems to point to a directory rather than a file. You can look in the file specified by  `--caliper-networkconfig` to see what your `configBinary` file is and check out that file to find out why a directory is there instead of a file.

Note: I got the same issue when running Caliper with Hyperledger Fabric when I had a mismatch of the `configtxgen` and `configtx.yaml` versions because my `FABRIC_CFG_PATH` environment variable was set to a different directory for some other stuff I was doing with Fabric. When I re-ran ./generate.sh after setting `FABRIC_CFG_PATH=""` and then re-launched it worked.

**Comment by davidkel** [comment]
Closing as old and no followup from the author
